// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.user_id", "5b4448b5-71d6-4f0d-849f-2ae9f60c08a2");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1532441290);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1532441410);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1532440930);
user_pref("app.update.lastUpdateTime.experiments-update-timer", 1532441170);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1532441650);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1532441050);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1532441770);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1532441530);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.capacity", 358400);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.cache.disk.smart_size.first_run", false);
user_pref("browser.cache.frecency_experiment", 2);
user_pref("browser.download.panel.shown", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1532440901);
user_pref("browser.laterrun.bookkeeping.sessionCount", 3);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 68);
user_pref("browser.newtabpage.activity-stream.impressionId", "{acdcb410-0fda-4a8f-badb-acfa46608841}");
user_pref("browser.newtabpage.activity-stream.migrationLastShownDate", 1532543400);
user_pref("browser.newtabpage.activity-stream.migrationRemainingDays", 2);
user_pref("browser.newtabpage.enhanced", true);
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.onboarding.notification.last-time-of-changing-tour-sec", 1532441991);
user_pref("browser.onboarding.notification.prompt-count", 3);
user_pref("browser.onboarding.notification.tour-ids-queue", "onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser,onboarding-tour-performance,onboarding-tour-private-browsing,onboarding-tour-screenshots,onboarding-tour-addons,onboarding-tour-customize,onboarding-tour-default-browser");
user_pref("browser.onboarding.seen-tourset-version", 2);
user_pref("browser.onboarding.tour-type", "new");
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"sendToDevice\",\"pocket\",\"screenshots\",\"addSearchEngine\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.places.smartBookmarksVersion", 8);
user_pref("browser.rights.3.shown", true);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1532442679742");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1532444452742");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1532441902514");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1532445502514");
user_pref("browser.search.countryCode", "IN");
user_pref("browser.search.region", "IN");
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20180704194937");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1532440905");
user_pref("browser.slowStartup.averageTime", 7196);
user_pref("browser.slowStartup.samples", 3);
user_pref("browser.startup.homepage_override.buildID", "20180704194937");
user_pref("browser.startup.homepage_override.mstone", "61.0.1");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"PersonalToolbar\":[\"personal-bookmarks\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"PersonalToolbar\",\"nav-bar\",\"TabsToolbar\",\"toolbar-menubar\"],\"currentVersion\":14,\"newElementCount\":2}");
user_pref("browser.urlbar.matchBuckets", "general:5,suggestion:Infinity");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("browser.urlbar.timesBeforeHidingSuggestionsHint", 0);
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "61.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("experiments.activeExperiment", false);
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", -1);
user_pref("extensions.databaseSchema", 26);
user_pref("extensions.getAddons.cache.lastUpdate", 1532441293);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.lastAppBuildId", "20180704194937");
user_pref("extensions.lastAppVersion", "61.0.1");
user_pref("extensions.lastPlatformVersion", "61.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.webextensions.uuids", "{\"screenshots@mozilla.org\":\"737f1056-d86b-45e9-8a8c-f2136ca76bf5\",\"webcompat@mozilla.org\":\"f475a561-4a6a-4094-b441-158f009f2e3a\"}");
user_pref("font.internaluseonly.changed", false);
user_pref("gecko.handlerService.migrated", true);
user_pref("idle.lastDailyNotification", 1532441424);
user_pref("lightweightThemes.usedThemes", "[]");
user_pref("media.gmp-manager.buildID", "20180208175058");
user_pref("media.gmp-manager.lastCheck", 1532441122);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.cookie.prefsMigrated", true);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.initialized", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("places.database.lastMaintenance", 1532441424);
user_pref("places.history.expiration.transient_current_max_pages", 104858);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "65ac424a-84b0-416e-9264-4ef12c19fd0b");
user_pref("services.blocklist.addons.checked", 1532424365);
user_pref("services.blocklist.clock_skew_seconds", 17045);
user_pref("services.blocklist.gfx.checked", 1532424365);
user_pref("services.blocklist.last_etag", "\"1532424286908\"");
user_pref("services.blocklist.last_update_seconds", 1532424365);
user_pref("services.blocklist.onecrl.checked", 1532424365);
user_pref("services.blocklist.pinning.checked", 1532424365);
user_pref("services.blocklist.plugins.checked", 1532424365);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1532441424);
user_pref("toolkit.startup.last_success", 1532575186);
user_pref("toolkit.telemetry.cachedClientID", "ddea73d3-f6e6-429f-b0f1-dd1920656775");
user_pref("toolkit.telemetry.previousBuildID", "20180704194937");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
